name: CI with Docker Compose

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.stats()'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        sleep 15  # wait for services to start
        curl -f http://localhost:3000 || exit 1

    - name: Tear down
      if: always()
      run: docker-compose down
